# Generated by Django 3.2.20 on 2023-08-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract', to='profiles.address'),
        ),
    ]
