# Generated by Django 3.2.20 on 2023-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
