# Generated by Django 3.2.20 on 2023-08-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_category', models.CharField(choices=[('smartphone', '스마트폰'), ('tablet', '태블릿'), ('laptop', '노트북')], max_length=20)),
                ('model_name', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=256)),
                ('sender_name', models.CharField(max_length=256)),
                ('sender_phone', models.CharField(max_length=64)),
                ('sender_address', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
