# Generated by Django 3.2.20 on 2023-08-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='content',
        ),
        migrations.AlterField(
            model_name='donation',
            name='sender_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='profiles.address'),
        ),
    ]
