# Generated by Django 3.2.20 on 2023-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20230818_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='model_category',
            field=models.CharField(choices=[('스마트폰', '스마트폰'), ('태블릿', '태블릿'), ('노트북', '노트북')], max_length=20),
        ),
    ]
