# Generated by Django 3.2.20 on 2023-08-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('reward', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('regist_start_at', models.DateField()),
                ('regist_end_at', models.DateField()),
                ('activity_start_at', models.DateField()),
                ('activity_end_at', models.DateField()),
                ('subscriber_limit', models.IntegerField()),
                ('activity_category', models.CharField(blank=True, choices=[('스마트폰 사용법', '스마트폰 사용법'), ('SNS 활용법', 'SNS 활용법'), ('유튜브 활용법', '유튜브 활용법'), ('키오스크 활용', '키오스크 활용')], max_length=100)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(related_name='program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
